# Generated by Django 6.1.1 on 2026-09-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_end_year_experience_is_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='end_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bulan akhir (1-12)', null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bulan awal (1-12)', null=True),
        ),
    ]
