# Generated by Django 6.1.1 on 2026-09-14 00:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_experience_end_month_experience_start_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('web-dev', 'Web Development'), ('mobile-dev', 'Mobile Development'), ('data-science', 'Data Science & AI'), ('ui-ux', 'UI/UX Design'), ('iot', 'Internet of Things'), ('other', 'Other')], default='web-dev', max_length=50)),
                ('tech_stack', models.CharField(blank=True, help_text='Contoh: Django, Python, PostgreSQL, Tailwind', max_length=255)),
                ('repository_url', models.URLField(blank=True, help_text='Link ke GitHub/GitLab repository', null=True)),
                ('demo_url', models.URLField(blank=True, help_text='Link ke live demo aplikasi', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
