# Generated by Django 6.1.1 on 2026-09-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
    ]
